@startuml
class ErrorMessage {
    + Type : MessageType <<get>>
    + MessageId : ushort <<get>>
    + Sender : string <<get>>
    + ErrorContent : string <<get>>
}
IMessage <|-- ErrorMessage
@enduml
