@startuml
!include ./CLArgumentsParser.puml
!include ./TcpChatClient.puml
!include ./IChatClient.puml
!include ./UdpChatClient.puml
!include ./ExitHandler.puml
!include ./Program.puml
!include ./Commands/AuthCommand.puml
!include ./Commands/RenameCommand.puml
!include ./Commands/ByeCommand.puml
!include ./Commands/CommandFactory.puml
!include ./Commands/Command.puml
!include ./Commands/ChatCommand.puml
!include ./Commands/JoinCommand.puml
!include ./Commands/HelpCommand.puml
!include ./Enums/ClientState.puml
!include ./Enums/ClientProtocolType.puml
!include ./Enums/MessageType.puml
!include ./Enums/ExitCode.puml
!include ./Messages/MessageParser.puml
!include ./Messages/UnknownMessage.puml
!include ./Messages/ByeMessage.puml
!include ./Messages/ConfirmMessage.puml
!include ./Messages/PingMessage.puml
!include ./Messages/ErrorMessage.puml
!include ./Messages/IMessage.puml
!include ./Messages/ChatMessage.puml
!include ./Messages/JoinMessage.puml
!include ./Messages/AuthMessage.puml
!include ./Messages/ReplyMessage.puml
!include ./Messages/MessageBuilder.puml
!include ./Constants/RegexPatterns.puml
!include ./obj/Release/linux-x64/.NETCoreApp,Version=v9.0.AssemblyAttributes.puml
!include ./obj/Release/linux-x64/Client.GlobalUsings.g.puml
!include ./obj/Release/linux-x64/Client.AssemblyInfo.puml
!include ./obj/Debug/linux-x64/.NETCoreApp,Version=v9.0.AssemblyAttributes.puml
!include ./obj/Debug/linux-x64/Client.GlobalUsings.g.puml
!include ./obj/Debug/linux-x64/Client.AssemblyInfo.puml
@enduml
